### ISSUE TITLE
회원 탈퇴 기능 구현

### ISSUE THREAD

**Issue by PhilSoGooood** [fourhe/backend#24]
## 📃 Description
회원 탈퇴 기능을 구현한다.

## ☑ Todo
- [x] 회원 탈퇴 시 하드 딜리트로 유저의 정보를 삭제한다.
- [x] 회원 탈퇴 시 이미 보낸 편지들은 삭제되지 않는다.
- [x] 보낸 편지들 외에 mailbox, trash 등 중간 테이블의 객체들은 삭제된다.
