### ISSUE TITLE
답장을 받으면 유저에게 이메일로 알림을 보낸다.

### ISSUE THREAD

**Issue by PhilSoGooood** [fourhe/backend#29]
## 📃 Description
답장을 받으면 유저에게 이메일로 알림을 보낸다.

## ☑ Todo
- [x] aws ses 계정 설정
- [x] aws ses 의존성 추가
- [x] 메일전송 로직 추가

## etc
이메일의 내용은?
